global using FluentValidation;
global using Storage.Infrastructure.Dtos;
global using System.Net;
global using AutoMapper;
global using Storage.Core.Models;
global using Storage.Core.Interfaces;
global using Storage.Infrastructure.Interfaces;
global using Storage.Infrastructure.Exceptions;
global using Microsoft.Extensions.Logging;
